# Nome do seu fluxo de trabalho. Aparecerá na aba "Actions" do seu repositório.
name: Executar Testes Cypress

# Define o gatilho (trigger) para o workflow.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define os "jobs" (tarefas) que serão executados.
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Define uma versão LTS ativa do Node para evitar conflitos no runner
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6

      # Armazenar capturas de tela somente se houver falhas
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Armazenar vídeos somente se houver falhas
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore



